In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
%matplotlib inline

# Getting the Data

In [2]:
DATASET_PATH = '/home/alk/aau/datasets'

# 6 dataset (1 per gateway) w/ 7 spreadsheets (1 per day)
LOLLAND_PATH_BS_1 = os.path.join(DATASET_PATH, 'Lolland/LRR689')
LOLLAND_PATH_BS_2 = os.path.join(DATASET_PATH, 'Lolland/LRR68D')
LOLLAND_PATH_BS_3 = os.path.join(DATASET_PATH, 'Lolland/LRR68F')
LOLLAND_PATH_BS_4 = os.path.join(DATASET_PATH, 'Lolland/LRR690')
LOLLAND_PATH_BS_5 = os.path.join(DATASET_PATH, 'Lolland/LRR698')
LOLLAND_PATH_BS_6 = os.path.join(DATASET_PATH, 'Lolland/LRR69F')

LOLLAND_EXCEL = 'data.xlsx'

In [3]:
def load_data_from_xlsx(path, xlsx_file, header=0):
    """Returns data frame of concatenated spreadsheets from loaded xlsx file"""
    xlsx_path = os.path.join(path, xlsx_file)
    df = pd.read_excel(xlsx_path, sheet_name=None, ignore_index=True, header=header)
    df_concat = pd.concat(df.values(), ignore_index=True)
    return df_concat

In [4]:
# data of each basestation during 7 days of measuring
data_bs_1 = load_data_from_xlsx(LOLLAND_PATH_BS_1, LOLLAND_EXCEL, header=1)
data_bs_2 = load_data_from_xlsx(LOLLAND_PATH_BS_2, LOLLAND_EXCEL, header=1)
data_bs_3 = load_data_from_xlsx(LOLLAND_PATH_BS_3, LOLLAND_EXCEL, header=1)
data_bs_4 = load_data_from_xlsx(LOLLAND_PATH_BS_4, LOLLAND_EXCEL, header=1)
data_bs_5 = load_data_from_xlsx(LOLLAND_PATH_BS_5, LOLLAND_EXCEL, header=1)
data_bs_6 = load_data_from_xlsx(LOLLAND_PATH_BS_6, LOLLAND_EXCEL, header=1)

In [5]:
# one big dataset
bigdata = data_bs_1.append(data_bs_2, 
    ignore_index=True).append(data_bs_3, 
    ignore_index=True).append(data_bs_4,
    ignore_index=True).append(data_bs_5, 
    ignore_index=True).append(data_bs_6,
    ignore_index=True)

# Preprocessing

In [6]:
# removing columns with all NaN values
bigdata = bigdata.dropna(axis=1, how='all')

In [7]:
bigdata.head()

,Direction,Timestamp,Timestamp(ISO),DevEUI,DevAddr,FPort,FCnt,LRR RSSI,LRR SNR,LRR ESP,...,DownlinkFailedCauseOnRX2,DownlinkFailedCauseOnPingSlot,Late,SolvLAT,SolvLON,PayloadSize,ISMBand,Modulation,SubID,ASID
0,1,2018-08-31 21:58:10.676,2018-08-31T21:58:10.676Z,70B3D5B020036E12,E013C68B,0,16.0,NaN,NaN,NaN,...,00,00,-,-,-,0,eu868,NaN,100014020,NaN
1,0,2018-08-31 21:58:10.551,2018-08-31T21:58:10.551Z,70B3D5B02003767B,E0125ADA,25,17.0,-108.0,-15.75,-123.864044,...,-,-,0,NaN,NaN,11,eu868,0.0,100014020,TWA_100014020.18310.AS
2,0,2018-08-31 21:58:08.676,2018-08-31T21:58:08.676Z,70B3D5B020036E12,E013C68B,24,19.0,-107.0,-2.00,-111.124430,...,-,-,0,NaN,NaN,11,eu868,0.0,100014020,TWA_100014020.18310.AS
3,1,2018-08-31 21:57:22.499,2018-08-31T21:57:22.499Z,70B3D5B020037673,E013FFE4,24,14.0,NaN,NaN,NaN,...,00,00,-,-,-,0,eu868,NaN,100014020,NaN
4,0,2018-08-31 21:57:20.499,2018-08-31T21:57:20.499Z,70B3D5B020037673,E013FFE4,24,19.0,-111.0,-13.25,-124.450775,...,-,-,0,NaN,NaN,11,eu868,0.0,100014020,TWA_100014020.18310.AS

In [8]:
bigdata.columns.values.tolist()

['Direction',
 'Timestamp',
 'Timestamp(ISO)',
 'DevEUI',
 'DevAddr',
 'FPort',
 'FCnt',
 'LRR RSSI',
 'LRR SNR',
 'LRR ESP',
 'SpFact',
 'SubBand',
 'Channel',
 'LRC Id',
 'LRR Id',
 'LRR Lat',
 'LRR Lon',
 'LRR Count',
 'LRR[1] Id',
 'LRR[1] RSSI',
 'LRR[1] SNR',
 'LRR[1] ESP',
 'LRR[1] CHAINS',
 'LRR[2] Id',
 'LRR[2] RSSI',
 'LRR[2] SNR',
 'LRR[2] ESP',
 'LRR[2] CHAINS',
 'LRR[3] Id',
 'LRR[3] RSSI',
 'LRR[3] SNR',
 'LRR[3] ESP',
 'LRR[3] CHAINS',
 'MAC(hex)',
 'MType',
 'ADR',
 'ADRACkReq',
 'Ack',
 'FPending(downlink)',
 'AirTime',
 'MIC',
 'Payload(hex)',
 'FCntUp',
 'FCntDn',
 'DownlinkStatus',
 'DownlinkFailedCauseOnRX1',
 'DownlinkFailedCauseOnRX2',
 'DownlinkFailedCauseOnPingSlot',
 'Late',
 'SolvLAT',
 'SolvLON',
 'PayloadSize',
 'ISMBand',
 'Modulation',
 'SubID',
 'ASID']

In [9]:
headers = ['Timestamp',
           'Direction', # downlink = 1; uplink = 0
           'DevAddr', # end device identification
           'LRC Id', 'LRR Id', # network server and base station identification
           'LRR Lat', 'LRR Lon', # base station location
           'LRR RSSI', 'LRR SNR', 'LRR ESP', # strength indicators
           'MIC', 'MType',
           'PayloadSize',
           'AirTime', # ToA - dependign of SPF 
           'ADR',
           'SpFact','SubBand', 'Channel', # spreading factor, channel, BW
           'ISMBand',
          ]

In [10]:
bigdata = bigdata[headers]

In [11]:
bigdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152453 entries, 0 to 152452
Data columns (total 19 columns):
Timestamp      152453 non-null object
Direction      152453 non-null object
DevAddr        66755 non-null object
LRC Id         152453 non-null object
LRR Id         152453 non-null object
LRR Lat        71603 non-null float64
LRR Lon        71603 non-null float64
LRR RSSI       71603 non-null float64
LRR SNR        71603 non-null float64
LRR ESP        71603 non-null float64
MIC            109619 non-null object
MType          152453 non-null object
PayloadSize    152453 non-null object
AirTime        152453 non-null float64
ADR            152453 non-null object
SpFact         152453 non-null object
SubBand        152453 non-null object
Channel        152453 non-null object
ISMBand        66755 non-null object
dtypes: float64(6), object(13)
memory usage: 22.1+ MB

In [12]:
bigdata['Direction'] = pd.to_numeric(bigdata.Direction, errors='coerce')

In [13]:
bigdata['MType'] = pd.to_numeric(bigdata.MType, errors='coerce')

In [14]:
bigdata['PayloadSize'] = pd.to_numeric(bigdata.PayloadSize, errors='coerce')

In [15]:
bigdata['SpFact'] = pd.to_numeric(bigdata.SpFact, errors='coerce')

In [16]:
bigdata['ADR'] = pd.to_numeric(bigdata.ADR, errors='coerce')

In [17]:
bigdata['Bandwidth'] = 125

In [18]:
bigdata.Channel.unique()

array(['LC255', 'LC4', 'LC5', 'LC7', 'LC8', 'LC1', 'LC2', 'LC6', 'LC3',
       'LC0', 'LC132'], dtype=object)

In [19]:
headers = ['Timestamp',
           'Direction', # downlink = 1; uplink = 0
           'DevAddr', # end device identification
           'LRC Id', 'LRR Id', # network server and base station identification
           'LRR Lat', 'LRR Lon', # base station location
           'LRR RSSI', 'LRR SNR', 'LRR ESP', # strength indicators
           'MType',
           'PayloadSize',
           'AirTime', # ToA - dependign of SPF 
           'ADR',
           'SpFact',
           'Bandwidth'
          ]

In [20]:
bigdata = bigdata[headers]

In [21]:
bigdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152453 entries, 0 to 152452
Data columns (total 16 columns):
Timestamp      152453 non-null object
Direction      152453 non-null int64
DevAddr        66755 non-null object
LRC Id         152453 non-null object
LRR Id         152453 non-null object
LRR Lat        71603 non-null float64
LRR Lon        71603 non-null float64
LRR RSSI       71603 non-null float64
LRR SNR        71603 non-null float64
LRR ESP        71603 non-null float64
MType          152453 non-null int64
PayloadSize    152453 non-null int64
AirTime        152453 non-null float64
ADR            152453 non-null int64
SpFact         152453 non-null int64
Bandwidth      152453 non-null int64
dtypes: float64(6), int64(6), object(4)
memory usage: 18.6+ MB

In [22]:
bigdata = bigdata.query('Direction == 0') # only uplink

In [23]:
bigdata = bigdata.reset_index()

In [24]:
bigdata.columns

Index(['index', 'Timestamp', 'Direction', 'DevAddr', 'LRC Id', 'LRR Id',
       'LRR Lat', 'LRR Lon', 'LRR RSSI', 'LRR SNR', 'LRR ESP', 'MType',
       'PayloadSize', 'AirTime', 'ADR', 'SpFact', 'Bandwidth'],
      dtype='object')

In [25]:
final_columns = ['Timestamp', 'DevAddr', 'LRR Id', 'LRR Lat',
                 'LRR Lon', 'LRR RSSI', 'LRR SNR', 'LRR ESP', 'MType',
                 'PayloadSize', 'AirTime', 'ADR', 'SpFact', 'Bandwidth'
                ]
bigdata = bigdata[final_columns]

In [26]:
bigdata['sucess'] = np.where(bigdata['AirTime']<1, 1, 0)

# Split the Data

Stratiffied splitting based on the LRR Id.

In [27]:
bigdata['LRR_Id_encoded'], categories = bigdata['LRR Id'].factorize()

In [28]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(bigdata, bigdata.LRR_Id_encoded):
    strat_train_set = bigdata.loc[train_index]
    strat_test_set = bigdata.loc[test_index]

In [29]:
strat_test_set['LRR Id'].value_counts() / len(strat_test_set)

0000068F    0.454368
689         0.225403
690         0.122198
0000069F    0.117450
698         0.071853
0000068D    0.008728
Name: LRR Id, dtype: float64

In [30]:
bigdata['LRR Id'].value_counts() / len(bigdata)

0000068F    0.454394
689         0.225410
690         0.122174
0000069F    0.117439
698         0.071855
0000068D    0.008729
Name: LRR Id, dtype: float64

In [31]:
strat_test_set

,Timestamp,DevAddr,LRR Id,LRR Lat,LRR Lon,LRR RSSI,LRR SNR,LRR ESP,MType,PayloadSize,AirTime,ADR,SpFact,Bandwidth,sucess,LRR_Id_encoded
21318,2018-08-30 19:28:43.000,E013D340,0000068F,54.923389,11.211714,-116.0,-19.00,-135.054340,4,11,1.318912,1,12,125,0,2
34416,2018-08-28 18:40:07.000,NaN,0000068F,54.923389,11.211714,-116.0,-11.00,-127.331955,0,0,0.133632,0,8,125,1,2
25188,2018-08-30 03:15:57.915,NaN,0000068F,54.923389,11.211714,-117.0,-7.00,-124.790100,0,0,0.071936,0,7,125,1,2
21670,2018-08-30 19:02:21.000,E0131915,0000068F,54.923389,11.211714,-116.0,-17.00,-133.085800,2,11,1.318912,1,12,125,0,2
35316,2018-08-27 21:27:51.000,NaN,0000068F,54.923306,11.211828,-117.0,-14.00,-131.169540,0,0,0.246784,0,9,125,1,2
5109,2018-08-28 20:00:14.141,NaN,689,54.759499,11.208343,-107.0,-18.25,-125.314500,0,0,1.646592,0,12,125,0,0
37916,2018-08-27 18:49:43.823,NaN,0000068F,54.923306,11.211828,-118.0,-11.25,-129.564040,0,0,0.133632,0,8,125,1,2
4000,2018-08-30 18:07:13.759,NaN,689,54.759972,11.212007,-98.0,6.50,-98.877360,0,0,0.071936,0,7,125,1,0
57479,2018-08-25 19:05:36.000,NaN,690,54.827953,11.162836,-108.0,-11.00,-119.331955,0,0,0.133632,0,8,125,1,3
58162,2018-08-29 16:52:20.000,E013E7AA,698,54.945103,11.398472,-115.0,-12.00,-127.265724,4,11,1.318912,1,12,125,0,4
19520,2018-08-31 18:25:46.000,NaN,0000068F,54.923389,11.211714,-114.0,0.00,-117.010300,0,0,0.071936,0,7,125,1,2
41856,2018-08-26 19:35:09.000,NaN,0000068F,54.923393,11.211711,-116.0,-10.00,-126.413925,0,0,0.452608,0,10,125,1,2
20508,2018-08-30 21:17:03.000,NaN,0000068F,54.923389,11.211714,-117.0,-19.00,-136.054340,0,0,0.823296,0,11,125,1,2
42340,2018-08-26 19:09:40.000,NaN,0000068F,54.923393,11.211711,-116.0,-16.00,-132.107740,0,0,1.646592,0,12,125,0,2
45597,2018-08-25 20:26:43.000,E012B9FC,0000068F,54.923393,11.211711,-116.0,-8.00,-124.638920,4,11,1.318912,1,12,125,0,2
49545,2018-08-31 19:49:16.000,E0127C91,690,54.827950,11.162862,-107.0,-17.00,-124.085800,4,11,1.318912,1,12,125,0,3
7196,2018-08-28 04:03:19.153,NaN,689,54.760120,11.207132,-111.0,-1.50,-114.824740,0,0,0.071936,0,7,125,1,0
3654,2018-08-30 18:29:28.012,NaN,689,54.760582,11.210451,-93.0,11.25,-93.314040,0,0,0.246784,0,9,125,1,0
2964,2018-08-30 20:13:56.987,E012312F,689,54.759785,11.212115,-105.0,-14.50,-119.651420,2,11,1.318912,1,12,125,0,0
9339,2018-08-27 18:45:03.022,NaN,689,54.759773,11.212013,-107.0,-5.00,-113.193310,0,0,0.133632,0,8,125,1,0
61938,2018-08-29 16:41:05.927,E0133F62,698,54.945103,11.398472,-115.0,-11.00,-126.331955,2,11,1.318912,1,12,125,0,4
27806,2018-08-29 19:44:35.495,NaN,0000068F,54.923389,11.211714,-115.0,-11.00,-126.331955,0,0,1.646592,0,12,125,0,2
15092,2018-08-25 18:45:39.851,NaN,689,54.759762,11.211946,-95.0,8.25,-95.605560,0,0,0.071936,0,7,125,1,0
49195,2018-08-25 03:09:22.846,NaN,0000068F,54.923344,11.211708,-116.0,-8.00,-124.638920,0,0,0.071936,0,7,125,1,2
49352,2018-08-31 21:14:35.000,E012A5E3,690,54.827950,11.162862,-108.0,-17.00,-125.085800,4,11,1.318912,1,12,125,0,3
19611,2018-08-31 04:02:43.000,NaN,0000068F,54.923389,11.211714,-116.0,-3.00,-120.764350,0,0,0.071936,0,7,125,1,2
53395,2018-08-28 19:16:57.000,NaN,690,54.827950,11.162862,-107.0,-16.00,-123.107740,0,0,0.452608,0,10,125,1,3
64821,2018-08-30 18:33:45.807,NaN,0000069F,54.693001,11.373283,-112.0,-19.00,-131.054340,0,0,1.646592,0,12,125,0,5
55463,2018-08-26 20:47:04.040,NaN,690,54.827953,11.162836,-110.0,-20.50,-130.538540,0,0,1.646592,0,12,125,0,3
21849,2018-08-30 18:49:41.000,NaN,0000068F,54.923389,11.211714,-117.0,-20.00,-137.043210,0,0,0.823296,0,11,125,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67163,2018-08-28 19:39:41.077,E0132418,0000069F,54.693001,11.373283,-110.0,-16.75,-126.840836,4,11,1.318912,1,12,125,0,5
53842,2018-08-28 03:44:43.000,NaN,690,54.827938,11.162833,-108.0,-21.00,-129.034360,0,0,1.646592,0,12,125,0,3
48789,2018-08-25 03:25:38.000,NaN,0000068F,54.923344,11.211708,-117.0,-18.00,-135.068300,0,0,0.823296,0,11,125,1,2
27332,2018-08-29 20:06:52.008,NaN,0000068F,54.923389,11.211714,-118.0,-9.00,-127.514970,0,0,0.071936,0,7,125,1,2
31850,2018-08-28 20:02:28.000,E0124B70,0000068F,54.923389,11.211714,-115.0,-14.00,-129.169540,4,14,1.318912,1,12,125,0,2
11905,2018-08-26 19:24:10.014,E0131C5C,689,54.759853,11.211786,-104.0,0.25,-106.887100,4,11,1.318912,1,12,125,0,0
22385,2018-08-30 18:17:04.000,NaN,0000068F,54.923389,11.211714,-117.0,-14.00,-131.169540,0,0,0.246784,0,9,125,1,2
14767,2018-08-25 19:06:36.668,NaN,689,54.759716,11.211795,-110.0,-8.25,-118.855560,0,0,0.133632,0,8,125,1,0
40334,2018-08-26 21:17:01.000,E013827C,0000068F,54.923393,11.211711,-117.0,-20.00,-137.043210,4,11,1.318912,1,12,125,0,2
57622,2018-08-25 18:50:39.688,NaN,690,54.827953,11.162836,-109.0,-11.00,-120.331955,0,0,0.452608,0,10,125,1,3
62066,2018-08-29 16:40:32.962,NaN,698,54.945103,11.398472,-115.0,-16.00,-131.107740,0,0,0.452608,0,10,125,1,4
48634,2018-08-25 03:35:19.000,NaN,0000068F,54.923344,11.211708,-117.0,-8.00,-125.638920,0,0,0.133632,0,8,125,1,2
61338,2018-08-29 16:42:36.662,NaN,698,54.945103,11.398472,-101.0,13.00,-101.212390,0,0,0.071936,0,7,125,1,4
45853,2018-08-25 20:11:12.000,NaN,0000068F,54.923393,11.211711,-116.0,-18.00,-134.068300,0,0,0.452608,0,10,125,1,2
11593,2018-08-26 19:51:53.085,E0124DF7,689,54.759853,11.211786,-95.0,6.00,-95.973230,4,4,0.046336,1,7,125,1,0
1757,2018-08-31 18:26:40.293,NaN,689,54.760139,11.210964,-105.0,3.75,-106.528070,0,0,0.071936,0,7,125,1,0
56906,2018-08-25 20:22:47.000,E013EFCC,690,54.827953,11.162836,-108.0,-21.00,-129.034360,2,11,1.318912,1,12,125,0,3
11555,2018-08-26 19:54:51.801,E013FFE4,689,54.759853,11.211786,-106.0,-15.50,-121.620705,4,11,1.318912,1,12,125,0,0
47752,2018-08-25 18:48:01.000,NaN,0000068F,54.923393,11.211711,-116.0,-6.00,-122.973230,0,0,0.071936,0,7,125,1,2
51293,2018-08-30 18:09:20.819,NaN,690,54.827950,11.162862,-110.0,-16.25,-126.351780,0,0,0.452608,0,10,125,1,3
53150,2018-08-28 19:56:38.761,NaN,690,54.827950,11.162862,-109.0,-17.50,-126.576550,0,0,0.823296,0,11,125,1,3
33868,2018-08-28 18:48:08.000,NaN,0000068F,54.923389,11.211714,-117.0,-15.00,-132.135210,0,0,0.823296,0,11,125,1,2
64673,2018-08-30 19:19:16.778,E01364D1,0000069F,54.693001,11.373283,-110.0,-21.00,-131.034360,4,14,1.318912,1,12,125,0,5
39865,2018-08-27 03:04:38.111,NaN,0000068F,54.923344,11.211801,-116.0,-8.00,-124.638920,0,0,0.071936,0,7,125,1,2
50710,2018-08-30 19:44:56.000,E0128EE1,690,54.827950,11.162862,-108.0,-21.00,-129.034360,4,14,1.318912,1,12,125,0,3
45472,2018-08-25 20:35:05.131,NaN,0000068F,54.923393,11.211711,-118.0,-8.25,-126.855560,0,0,0.071936,0,7,125,1,2
15249,2018-08-25 18:42:16.415,NaN,689,54.759762,11.211946,-95.0,7.00,-95.790100,0,0,0.071936,0,7,125,1,0
458,2018-08-31 19:54:14.986,E012886B,689,54.759644,11.211551,-91.0,8.25,-91.605560,2,11,0.056576,1,7,125,1,0
59198,2018-08-29 16:49:17.965,E0136E13,698,54.945103,11.398472,-105.0,9.00,-105.514970,2,11,1.318912,1,12,125,0,4
40163,2018-08-26 21:32:28.000,E01268BA,0000068F,54.923344,11.211801,-117.0,-12.00,-129.265720,2,8,1.155072,1,12,125,0,2

# Data Cleaning

In [32]:
data = strat_train_set.drop('sucess', axis=1)
data_labels = strat_train_set['sucess'].copy()

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57282 entries, 27510 to 57877
Data columns (total 15 columns):
Timestamp         57282 non-null object
DevAddr           23111 non-null object
LRR Id            57282 non-null object
LRR Lat           57282 non-null float64
LRR Lon           57282 non-null float64
LRR RSSI          57282 non-null float64
LRR SNR           57282 non-null float64
LRR ESP           57282 non-null float64
MType             57282 non-null int64
PayloadSize       57282 non-null int64
AirTime           57282 non-null float64
ADR               57282 non-null int64
SpFact            57282 non-null int64
Bandwidth         57282 non-null int64
LRR_Id_encoded    57282 non-null int64
dtypes: float64(6), int64(6), object(3)
memory usage: 7.0+ MB

In [34]:
from sklearn.base import BaseEstimator, TransformerMixin

data_num = data[['MType', 'PayloadSize', 'ADR', 'SpFact', 'Bandwidth']].copy()
SpFact_ix, Bandwidth_ix = [
    list(data_num.columns).index(col)
    for col in ("SpFact", "Bandwidth")]

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, code_rate=0.8, add_data_rate=True):
        self.add_data_rate = add_data_rate
        self.code_rate = code_rate
    def fit(self, X, y=None):
        return self
    def transform(self, X, y=None):
        data_rate = X[:, SpFact_ix] * X[:, Bandwidth_ix] * self.code_rate / (np.power(2, X[:, SpFact_ix]))
        if self.add_data_rate:
            return np.c_[X, data_rate]
        else:
            return np.c_[self.code_rate]

attr_adder = CombinedAttributesAdder()
data_extra_attribs = attr_adder.transform(data.values)

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler()),
])

data_num_tr = num_pipeline.fit_transform(data_num)

In [36]:
num_attribs = ['MType', 'PayloadSize', 'ADR', 'SpFact', 'Bandwidth']
cat_attribs = ['LRR_Id_encoded']

class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names].values

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler()),
])

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(categories='auto'), cat_attribs),
])

data_prepared = full_pipeline.fit_transform(data)

# Training

In [80]:
from sklearn.linear_model import LogisticRegression

In [81]:
logreg = LogisticRegression(random_state=42)

In [82]:
logreg.fit(data_prepared, data_labels)

/home/alk/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=42, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [84]:
X_test = strat_test_set.drop('sucess',axis=1)
y_test = strat_test_set['sucess'].copy()

In [85]:
X_test_prepared = full_pipeline.transform(X_test)

In [87]:
y_pred = logreg.predict(X_test_prepared)
print('Accuracy of logistic regression classifier on test set:\
      {:.2f}'.format(logreg.score(X_test_prepared, y_test)))

Accuracy of logistic regression classifier on test set:      1.00